language: python
python: 
- 3.6
install:
- pip install -r doc/requirements.txt
- pip install pylint
script:
- pylint views.py
notifications:
    webhooks:
        urls:
            - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MHJpY2NvJTNBcHl0aG9uLnNrLyUyMUZtTUZreW9zZ3lJWWRwRExRZyUzQXB5dGhvbi5zaw"
        on_success: change  # always|never|change
        on_failure: always
        on_start: never

